#directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-12-21-12-03-42_ekf_paper'
#directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-12-21-12-03-42_ekf_own'
origin_coordinates:
  lat: 38.275064630154375
  lon: -0.6861944724090255


directory: '/home/arvc/Juanjo/Datasets/KittiDataset/sequences/03'

#directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-12-07-15-22-43'
do_offline_ekf: False
scan_idx: 0

overlap:
  save_as: '3d_overlap_kitti07'
  radius: 0.25

experiment:
#  deltaxy: 1
#  deltath: 0.3
  deltaxy: 1
  deltath: 0
#  deltath: 0.2
  long: null # Number or None

local_environment:
  dist: 10 # meters
  angle: 90 # degrees

gps:
  reference_status: 2 # 2 rtk






