#directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-12-21-12-03-42_ekf_paper'
#directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-12-21-12-03-42_ekf_own'
directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-12-07-15-22-43'
save_overlap_in: 'ekf_overlap'

do_offline_ekf: False
scan_idx: 0

experiment:
  deltaxy: 1
#  deltath: 0.3
  deltath: 0.2
  long: null # Number or None
  local_environment: 30

gps:
  reference_status: 2 # 2 rtk




