#directory: '/home/arvc/Escritorio/develop/Registration/dos_vueltas_features/'
directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-11-30-15-30-57'
#directory: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Entorno_inicial_secuencia1'
down_sample:
#  voxel_size: 0.03 # Number or None
  voxel_size: 0.03 # Number or null

filter_by_distance:
  max_distance: 35
  min_distance: 0.5
filter_ground_plane:
  radius_normals: 3
  maximum_neighbors: 200

normals:
  maximum_neighbors: 50
  radius_normals: 0.5

fpfh:
  fpfh_threshold: 5

descriptor:
  max_radius_descriptor: 60

icp:
  distance_threshold: 5

experiment:
  deltaxy: 0.2
#  deltath: 0.3
  deltath: 0.1
  long: null # Number or None

gps:
  reference_status: 2 # 1 sps, 2 gps, 3 and 4 rtk
