training_path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'
ground_truth_path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'
validation_path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'
testing_path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'

parallel_computing: False
max_ngpu: 3

fixed_n_points:
  sample2n: False
  n_points: 4096
  max_radius: 120

output_size: 32
training_parameters:
  batch_size: 32
  number_epochs: 1

