testing_path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'

parallel_computing: False
max_ngpu: 3

input_data_preprocessing:
  sample2n: False
  n_points: 4096
  max_radius: 120
  normalize_coords: True

output_data:
  embedding_size: 32
  normalize_embeddings: False

training_parameters:
  path: '/home/arvc/Escritorio/develop/Rosbags_Juanjo/Exterior_innova/2022-12-07-15-22-43'
  batch_size: 8
  number_epochs: 1

validation_parameters:
#  path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2023-01-24-12-25-00'
  path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-21-12-03-42'
#  path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2023-01-24-18-59-02'
  batch_size: 32

groundtruth_parameters:
  path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'
  batch_size: 32

evaluation_parameters:
  success_boundary_radius: 25 #meters
