testing_path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'

parallel_computing: False
max_ngpu: 3

fixed_n_points:
  sample2n: False
  n_points: 4096
  max_radius: 120

output_size: 32

training_parameters:
  path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'
  batch_size: 8
  number_epochs: 1

validation_parameters:
  path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-21-12-03-42'
  batch_size: 32

groundtruth_parameters:
  path: '/home/arvc/Juanjo/Datasets/Exterior_innova/2022-12-07-15-22-43'
  batch_size: 32
